/**
 * Turns a corpus replay JSONL into the markdown table that goes in docs/replay.md.
 *
 *   node scripts/corpus-table.mjs docs/corpus/tuning-2026-09-10.jsonl
 *
 * This exists because the table was previously written by hand, and on 2026-09-10 a docs-only commit replaced
 * numbers the script produced with numbers it does not: the flask row went from "test-deleted 23, assertion-weakened
 * 4" to "test-deleted 7, assertion-weakened 1", understating the blocking rate about threefold. Nothing in the code
 * changed, so nothing caught it. A table generated from the record cannot drift from the record.
 *
 * Two rates, because they answer different questions:
 *   - blocking commits / all commits — what fraction of a maintainer's commits the gate would interrupt.
 *   - blocking commits / test-touching commits — comparable to the older published table, which used that base.
 *
 * Neither is a false-positive rate. Nobody has labelled these commits, and the residual is largely `test-deleted` on
 * commits that genuinely deleted a test, which is the rule working. This is an upper bound on false positives and a
 * measurement of the interruption a user would feel.
 */
import fs from 'node:fs';

const file = process.argv[2];
if (!file) { console.error('usage: node scripts/corpus-table.mjs <replay.jsonl>'); process.exit(2); }

const rows = fs.readFileSync(file, 'utf8').split('\n').filter(Boolean).map((l) => JSON.parse(l));
const run = rows.find((r) => r.kind === 'run');
const byRepo = new Map();
for (const r of rows) {
  if (r.kind !== 'commit') continue;
  const s = byRepo.get(r.repo) ?? { repo: r.repo, commits: 0, touching: 0, blockingCommits: 0, blockingTouching: 0, findings: 0, blockingByRule: {}, blockingCommitsByRule: {} };
  s.commits++;
  if (r.touchesTests) s.touching++;
  s.findings += r.findings.length;
  const blocks = r.findings.filter((f) => f.severity === 'block');
  if (blocks.length) { s.blockingCommits++; if (r.touchesTests) s.blockingTouching++; }
  for (const f of blocks) s.blockingByRule[f.rule] = (s.blockingByRule[f.rule] ?? 0) + 1;
  for (const rule of new Set(blocks.map((b) => b.rule))) s.blockingCommitsByRule[rule] = (s.blockingCommitsByRule[rule] ?? 0) + 1;
  byRepo.set(r.repo, s);
}

const meta = new Map(rows.filter((r) => r.kind === 'repo').map((r) => [r.repo, r]));
const pct = (a, b) => (b === 0 ? '—' : `${((a / b) * 100).toFixed(1)}%`);
const rules = (m) => Object.entries(m).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k} ${v}`).join(', ') || '—';

console.log(`<!-- Generated by scripts/corpus-table.mjs from ${file}. Do not edit by hand. -->`);
console.log(`<!-- gatekeep ${run?.gatekeep?.version ?? '?'}, ${run?.gatekeep?.rules ?? '?'} rules, config ${run?.gatekeep?.sha256 ?? '?'}, run ${run?.date?.slice(0, 10) ?? '?'} -->`);
console.log();
console.log('| Repo | Lang | Commits | Touching tests | Findings | Commits a block would stop | Of test-touching | Blocking findings, by rule |');
console.log('|---|---|---|---|---|---|---|---|');
const t = { commits: 0, touching: 0, blockingCommits: 0, blockingTouching: 0, findings: 0 };
for (const s of byRepo.values()) {
  const m = meta.get(s.repo);
  t.commits += s.commits; t.touching += s.touching; t.blockingCommits += s.blockingCommits;
  t.blockingTouching += s.blockingTouching; t.findings += s.findings;
  console.log(`| [${s.repo}](https://github.com/${s.repo}) \`${(m?.head ?? '').slice(0, 8)}\` | ${m?.lang ?? ''} | ${s.commits} | ${s.touching} | ${s.findings} | ${s.blockingCommits} (${pct(s.blockingCommits, s.commits)}) | ${s.blockingTouching} (${pct(s.blockingTouching, s.touching)}) | ${rules(s.blockingByRule)} |`);
}
console.log(`| **total** | | **${t.commits}** | **${t.touching}** | **${t.findings}** | **${t.blockingCommits} (${pct(t.blockingCommits, t.commits)})** | **${t.blockingTouching} (${pct(t.blockingTouching, t.touching)})** | |`);
console.log();

const all = {};
for (const s of byRepo.values()) for (const [k, v] of Object.entries(s.blockingCommitsByRule)) all[k] = (all[k] ?? 0) + v;
console.log('Blocking **commits** by rule across the set (a commit that deletes eleven tests counts once):');
console.log();
for (const [k, v] of Object.entries(all).sort((a, b) => b[1] - a[1])) console.log(`- \`${k}\` — ${v} commit${v === 1 ? '' : 's'}`);
